[package]
name = "MineAway"
version = "0.1.0"
authors = ["TheCowKing-moo- <derrekschuurman@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
specs = "0.14"
specs-derive = "0.4"

[dependencies.sdl2]
version = "*"
default-features = false
features = ["image"]
